# Generated by Django 5.2.14 on 2026-05-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(max_length=200)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('affected_url', models.CharField(max_length=300)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
