# Generated by Django 5.2.14 on 2026-05-21 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='allowed_modules',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to allow access to all SAP modules.', related_name='departments', to='knowledge.sapmodule'),
        ),
        migrations.CreateModel(
            name='DepartmentChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_left', to='accounts.department')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_joined', to='accounts.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department Change Log',
                'ordering': ['-changed_at'],
            },
        ),
    ]
